# Generated by Django 2.2.5 on 2019-09-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_manager', '0002_auto_20190917_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
