# Generated by Django 2.2.5 on 2019-09-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_manager', '0003_auto_20190917_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token_validity',
            new_name='token_expires_in',
        ),
    ]
