# Generated by Django 2.2.5 on 2019-09-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_manager', '0004_auto_20190918_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
