# Generated by Django 2.2.5 on 2019-09-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_manager', '0005_user_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='unique_identifier',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
