# Generated by Django 2.2.5 on 2019-09-24 04:30

from django.db import migrations, models
import project.room_manager.models.room


class Migration(migrations.Migration):

    dependencies = [
        ('room_manager', '0006_auto_20190924_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Room name', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='location_latitude',
            field=models.DecimalField(decimal_places=5,
                                      max_digits=8,
                                      null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='location_longitude',
            field=models.DecimalField(decimal_places=5,
                                      max_digits=8,
                                      null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='unique_identifier',
            field=models.CharField(
                default=project.room_manager.models.room.Room.generate_id,
                max_length=5,
                unique=True),
        ),
    ]
