# Generated by Django 2.2.5 on 2019-09-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_manager', '0008_auto_20190926_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='alive',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DEAD'),
                                                            (1, 'ALIVE')],
                                                   default=0),
        ),
    ]
